server:
  port: 9999

com:
  sms:
    ok:com.sms.ok

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sms-server

  # 数据源配置
  datasource:
    url: jdbc:mysql://47.129.32.100:16306/smsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: bzdfCde412GHYD
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 18800
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # Redis 配置
  data:
    redis:
      host: 47.129.32.100
      port: 16379
      # password: 123456  # 若需密码可取消注释

  # Kafka 配置
  kafka:
    bootstrap-servers: 47.129.32.100:9092,47.129.32.100:9093,47.129.32.100:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        max.block.ms: 60000
        request.timeout.ms: 30000
        enable.idempotence: true
        compression.type: snappy
        linger.ms: 10
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed
      max-poll-records: 500
      fetch-max-wait: 500
      heartbeat-interval: 3000
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      properties:
        spring.json.trusted.packages: com.sms.ok.sms.dto
        spring.json.use.type.headers: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 1
      type: SINGLE
      poll-timeout: 5000


# MyBatis-Plus 配置（新增）
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sms.ok.module.*.dal.dataobject

# 自定义配置
imageSavePath: ./img/
botChatId: -4889920165
botMoneyChatId: -4889920165
botToken: 7962178261:AAHfbdIDj--bzwNVYL3cTBnkh4aw3iSNnr8
botName: SMS_intelligent_robot_bot

sms:
  info:
    base-package: com.sms.ok.sms  # 根据您的实际包结构修改
  framework:
    web:
      enable: true
    mybatis:
      enable: true
  sender:
    topic: sms-message-topic
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000
    batch-size: 50
    rate-limit: 1000
  receiver:
    topic: sms-receiver-topic
  report:
    topic: sms-report-topic
  web:
    admin-api:
      prefix: /admin-api
      controller: com.sms.ok.module.*.controller
    app-api:
      prefix: /app-api
      controller: com.sms.ok.module.*.controller
    admin-ui: /admin
